// <auto-generated />
using System;
using CryptoBank.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoBank.Persistence.Migrations
{
    [DbContext(typeof(CryptoBankDbContext))]
    [Migration("20260605133741_AddNewTablesAndSeedData")]
    partial class AddNewTablesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoBank.Domain.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Estonia"
                        });
                });

            modelBuilder.Entity("CryptoBank.Domain.Models.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "USD",
                            Name = "US Dollar",
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "EUR",
                            Name = "Euro",
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "UAH",
                            Name = "Ukrainian hryvnia",
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 4L,
                            Code = "BTC",
                            Name = "Bitcoin",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 5L,
                            Code = "ETH",
                            Name = "Ethereum",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 6L,
                            Code = "TRX",
                            Name = "Tronix",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 7L,
                            Code = "BNB",
                            Name = "Build and Build",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 8L,
                            Code = "USDT",
                            Name = "Tether USD",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 9L,
                            Code = "USDC",
                            Name = "USD Coin",
                            Type = (byte)2
                        });
                });

            modelBuilder.Entity("CryptoBank.Domain.Models.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RateToUsd")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CurrencyId = 1L,
                            RateToUsd = 1m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CurrencyId = 2L,
                            RateToUsd = 1.16m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CurrencyId = 3L,
                            RateToUsd = 0.023m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CurrencyId = 4L,
                            RateToUsd = 62229m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            CurrencyId = 5L,
                            RateToUsd = 1670m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6L,
                            CurrencyId = 6L,
                            RateToUsd = 0.33m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7L,
                            CurrencyId = 7L,
                            RateToUsd = 592.20m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8L,
                            CurrencyId = 8L,
                            RateToUsd = 1m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9L,
                            CurrencyId = 9L,
                            RateToUsd = 1m,
                            UpdatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CryptoBank.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptoBank.Domain.Models.ExchangeRate", b =>
                {
                    b.HasOne("CryptoBank.Domain.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("CryptoBank.Domain.Models.User", b =>
                {
                    b.HasOne("CryptoBank.Domain.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
